easy_admin:
  entities:
    # List the entity class name you want to manage
    Evenements:
      class: App\Entity\Event
    Roles:
      class: App\Entity\Role
    Utilisateurs:
      class: App\Entity\User
