nelmio_cors:
  defaults:
    # allow_credentials: false
    allow_origin: ["*"]
    allow_headers: ["*"]
    allow_methods: ["POST", "PUT", "GET", "DELETE", "PATCH", "OPTIONS"]
    # expose_headers: ['link']
    max_age: 3600
    # hosts: []
    origin_regex: false
    # forced_allow_origin_value: ~
  paths:
    "^/":
      allow_origin: ["*"]
      allow_headers: ["*"]
      allow_methods: ["POST", "PUT", "GET", "DELETE", "PATCH", "OPTIONS"]
      # expose_headers: ['link']
      max_age: 3600
      # hosts: []
      origin_regex: false

