vich_uploader:
    db_driver: orm

    mappings:
       images:
        uri_prefix: '%app.path.images%'
        upload_destination: '%app.path.images%'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
